### ISSUE TITLE
Product Page - Add Thumbnail Scroll Bar

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/enhancements#6]
Looks like (when 3+ thumbs)
<img width="655" alt="screen shot 2016-06-21 at 4 22 36 am" src="https://cloud.githubusercontent.com/assets/3649059/16222784/f5e1132a-3767-11e6-94b2-ede41e10c7de.png">

Let's add a scroll bar that cuts off flush with the bottom of the main image like this

<img width="658" alt="screen shot 2016-06-21 at 4 22 46 am" src="https://cloud.githubusercontent.com/assets/3649059/16222803/14312900-3768-11e6-9081-5a9b4724a166.png">

**Comment by EmilioTelevision** [comment]
I made thew side panels scrollable, added some styles to it because the track has some shadow and it looked weird on prdoucts that didnt have enough photots to scroll. The css is on line 4095 div .scroll-me in theme.scsss

![image](https://cloud.githubusercontent.com/assets/3394886/16319355/029e9dee-3961-11e6-9b77-7e54f3e9ad0e.png)
Removing the shadow the shadow so it doesn't show 
![image](https://cloud.githubusercontent.com/assets/3394886/16319398/254f7782-3961-11e6-8869-142b32ded96e.png)

**Comment by EmilioTelevision** [comment]
this might be the only option that works across the board
![image](https://cloud.githubusercontent.com/assets/3394886/16464590/dd910ce2-3e08-11e6-9890-d5e5ffb0471b.png)

**Comment by GVFTW** [comment]
closing and will fire back up when we're ready to try a new approach
